<?php

	$smarty->assign( "URI_PUBLIC", URI_PUBLIC );
	$smarty->assign( "URI_CSS", URI_CSS );
	$smarty->assign( "URI_JS", URI_JS );
	$smarty->assign( "URI_IMAGES", URI_IMAGES );
	$smarty->assign( "URI_FILES", URI_FILES );
	$smarty->assign( "URI_PUBLIC_ADMIN", URI_PUBLIC_ADMIN );
	$smarty->assign( "URI_CSS_ADMIN", URI_CSS_ADMIN );
	$smarty->assign( "URI_JS_ADMIN", URI_JS_ADMIN );
	$smarty->assign( "URI_IMAGES_ADMIN", URI_IMAGES_ADMIN );
	$smarty->assign( "PATH_PLUGIN", PATH_PLUGIN );
	$smarty->assign( "PATH_TEMPLATES", PATH_TEMPLATES );
	$smarty->assign( "PATH_TEMPLATES_ADMIN", PATH_TEMPLATES_ADMIN );
	$smarty->assign( "SCRIPT_NAME", SCRIPT_NAME );

	$smarty->assign( "month", Array(
		"long" => Array(
			"01" => "Janeiro",
			"02" => "Fevereiro",
			"03" => "Março",
			"04" => "Abril",
			"05" => "Maio",
			"06" => "Junho",
			"07" => "Julho",
			"08" => "Agosto",
			"09" => "Setembro",
			"10" => "Outubro",
			"11" => "Novembro",
			"12" => "Dezembro"
		),
		"small" => Array(
			"01" => "Jan",
			"02" => "Fev",
			"03" => "Mar",
			"04" => "Abr",
			"05" => "Mai",
			"06" => "Jun",
			"07" => "Jul",
			"08" => "Ago",
			"09" => "Set",
			"10" => "Out",
			"11" => "Nov",
			"12" => "Dez"
		)
	));

    $l_bank = Array(
        "001" => (Object)Array( "bank_code" => "001", "bank_name" => "BANCO DO BRASIL SA" ),
        //"002" => (Object)Array( "bank_code" => "002", "bank_name" => "BANCO CENTRAL DO BRASIL SA" ),
        //"003" => (Object)Array( "bank_code" => "003", "bank_name" => "BANCO DA AMAZONIA SA" ),
        //"004" => (Object)Array( "bank_code" => "004", "bank_name" => "BANCO DO NORDESTE DO BRASIL SA" ),
        //"007" => (Object)Array( "bank_code" => "007", "bank_name" => "BANCO NACIONAL DES. ECONOMICO SA" ),
        //"008" => (Object)Array( "bank_code" => "008", "bank_name" => "BANCO MERIDIONAL DO BRASIL SA" ),
        //"021" => (Object)Array( "bank_code" => "021", "bank_name" => "BANCO DO ESTADO DO ESPIRITO SANTO SA" ),
        //"022" => (Object)Array( "bank_code" => "022", "bank_name" => "BANCO DE CREDITO REAL DE MINAS GERAIS SA" ),
        //"024" => (Object)Array( "bank_code" => "024", "bank_name" => "BANCO DO ESTADO DE PERNAMBUCO SA" ),
        //"025" => (Object)Array( "bank_code" => "025", "bank_name" => "BANCO ALFA S/A" ),
        //"027" => (Object)Array( "bank_code" => "027", "bank_name" => "BANCO DO ESTADO DE SANTA CATARINA SA" ),
        //"028" => (Object)Array( "bank_code" => "028", "bank_name" => "BANCO DO ESTADO DA BAHIA SA" ),
        //"029" => (Object)Array( "bank_code" => "029", "bank_name" => "BANCO BANERJ S/A" ),
        //"030" => (Object)Array( "bank_code" => "030", "bank_name" => "BANCO PARAIBAN BCO DO EST.DA PARAIBA SA" ),
        //"031" => (Object)Array( "bank_code" => "031", "bank_name" => "BANCO DO ESTADO DE GOIAS SA" ),
        "033" => (Object)Array( "bank_code" => "033", "bank_name" => "BANCO SANTANDER BRASIL S.A." ),
        //"034" => (Object)Array( "bank_code" => "034", "bank_name" => "BANCO DO ESTADO DO AMAZONAS SA" ),
        //"035" => (Object)Array( "bank_code" => "035", "bank_name" => "BANCO DO ESTADO DO CEARA SA" ),
        //"036" => (Object)Array( "bank_code" => "036", "bank_name" => "BANCO DO ESTADO DO MARANHAO SA" ),
        //"037" => (Object)Array( "bank_code" => "037", "bank_name" => "BANCO DO ESTADO DO PARA SA" ),
        //"038" => (Object)Array( "bank_code" => "038", "bank_name" => "BANCO DO ESTADO DO PARANA SA" ),
        //"039" => (Object)Array( "bank_code" => "039", "bank_name" => "BANCO DO ESTADO DO PIAUI SA" ),
        //"040" => (Object)Array( "bank_code" => "040", "bank_name" => "BANCO CARGILL S/A" ),
        //"041" => (Object)Array( "bank_code" => "041", "bank_name" => "BANCO DO ESTADO DO RIO GRANDE DO SUL SA" ),
        //"042" => (Object)Array( "bank_code" => "042", "bank_name" => "BANCO J. SAFRA S/A" ),
        //"044" => (Object)Array( "bank_code" => "044", "bank_name" => "BANCO BVA S/A" ),
        //"047" => (Object)Array( "bank_code" => "047", "bank_name" => "BANCO DO ESTADO DE SERGIPE SA" ),
        //"048" => (Object)Array( "bank_code" => "048", "bank_name" => "BANCO BEMGE S.A." ),
        //"070" => (Object)Array( "bank_code" => "070", "bank_name" => "BANCO DE BRASILIA SA" ),
        //"085" => (Object)Array( "bank_code" => "085", "bank_name" => "VIACRED" ),
        "104" => (Object)Array( "bank_code" => "104", "bank_name" => "CAIXA ECONOMICA FEDERAL SA" ),
        //"106" => (Object)Array( "bank_code" => "106", "bank_name" => "BANCO ITABANCO S.A." ),
        //"107" => (Object)Array( "bank_code" => "107", "bank_name" => "BANCO BBM S.A" ),
        //"109" => (Object)Array( "bank_code" => "109", "bank_name" => "BANCO CREDIBANCO SA" ),
        //"112" => (Object)Array( "bank_code" => "112", "bank_name" => "UNICRED" ),
        //"116" => (Object)Array( "bank_code" => "116", "bank_name" => "BANCO BNL DO BRASIL S.A." ),
        //"136" => (Object)Array( "bank_code" => "136", "bank_name" => "UNICRED" ),
        //"148" => (Object)Array( "bank_code" => "148", "bank_name" => "MULTI BANCO SA" ),
        //"151" => (Object)Array( "bank_code" => "151", "bank_name" => "NOSSA CAIXA - NOSSO BANCO S/A" ),
        //"168" => (Object)Array( "bank_code" => "168", "bank_name" => "BANCO CCF DO BRASIL SA" ),
        //"175" => (Object)Array( "bank_code" => "175", "bank_name" => "BANCO CONTINENTAL SA" ),
        //"184" => (Object)Array( "bank_code" => "184", "bank_name" => "BANCO BBA-CREDITANSTALT SA" ),
        //"200" => (Object)Array( "bank_code" => "200", "bank_name" => "BANCO FICRISA AXELRUD SA" ),
        //"201" => (Object)Array( "bank_code" => "201", "bank_name" => "BANCO AXIAL SA" ),
        //"204" => (Object)Array( "bank_code" => "204", "bank_name" => "BANCO INTER AMERICAN EXPRESS S.A." ),
        "205" => (Object)Array( "bank_code" => "205", "bank_name" => "BANCO SUL AMERICA SA" ),
        //"206" => (Object)Array( "bank_code" => "206", "bank_name" => "BANCO MARTINELLI SA" ),
        //"208" => (Object)Array( "bank_code" => "208", "bank_name" => "BANCO PACTUAL SA" ),
        //"210" => (Object)Array( "bank_code" => "210", "bank_name" => "DRESDNER BANK LATEINAMERIKA S.A" ),
        //"211" => (Object)Array( "bank_code" => "211", "bank_name" => "BANCO SISTEMA SA" ),
        //"212" => (Object)Array( "bank_code" => "212", "bank_name" => "BANCO MATONE SA" ),
        //"213" => (Object)Array( "bank_code" => "213", "bank_name" => "BANCO ARBI SA" ),
        //"214" => (Object)Array( "bank_code" => "214", "bank_name" => "BANCO DIBENS SA" ),
        //"215" => (Object)Array( "bank_code" => "215", "bank_name" => "BANCO AMERICA DO SUL SA" ),
        //"216" => (Object)Array( "bank_code" => "216", "bank_name" => "BANCO REGIONAL MALCON SA" ),
        //"217" => (Object)Array( "bank_code" => "217", "bank_name" => "BANCO JOHN DEERE S/A" ),
        //"218" => (Object)Array( "bank_code" => "218", "bank_name" => "BANCO BONSUCESSO S.A" ),
        //"219" => (Object)Array( "bank_code" => "219", "bank_name" => "BANCO ZOGBI S/A" ),
        //"221" => (Object)Array( "bank_code" => "221", "bank_name" => "BANCO FLEMING GRAPHUS S.A" ),
        //"222" => (Object)Array( "bank_code" => "222", "bank_name" => "BANCO AGF BRASIL SA" ),
        //"224" => (Object)Array( "bank_code" => "224", "bank_name" => "BANCO FIBRA SA" ),
        //"225" => (Object)Array( "bank_code" => "225", "bank_name" => "BANCO BRASCAN SA." ),
        //"228" => (Object)Array( "bank_code" => "228", "bank_name" => "BANCO ICATU SA" ),
        //"229" => (Object)Array( "bank_code" => "229", "bank_name" => "BANCO CRUZEIRO S.A." ),
        //"230" => (Object)Array( "bank_code" => "230", "bank_name" => "BANCO BANDEIRANTES SA" ),
        //"231" => (Object)Array( "bank_code" => "231", "bank_name" => "BANCO BOAVISTA INTERATLANTICO S.A." ),
        //"232" => (Object)Array( "bank_code" => "232", "bank_name" => "BANCO INTERPART S.A" ),
        //"233" => (Object)Array( "bank_code" => "233", "bank_name" => "BANCO GE CAPITAL S.A" ),
        //"234" => (Object)Array( "bank_code" => "234", "bank_name" => "BANCO LAVRA SA" ),
        //"235" => (Object)Array( "bank_code" => "235", "bank_name" => "BANCO LIBERAL SA" ),
        "237" => (Object)Array( "bank_code" => "237", "bank_name" => "BANCO BRADESCO S.A" ),
        //"241" => (Object)Array( "bank_code" => "241", "bank_name" => "BANCO CLASSICO SA" ),
        //"242" => (Object)Array( "bank_code" => "242", "bank_name" => "BANCO EUROINVEST SA" ),
        //"243" => (Object)Array( "bank_code" => "243", "bank_name" => "BANCO STOCK MAXIMA S.A." ),
        //"244" => (Object)Array( "bank_code" => "244", "bank_name" => "BANCO CIDADE SA" ),
        //"246" => (Object)Array( "bank_code" => "246", "bank_name" => "BANCO ABC BRASIL S.A" ),
        //"247" => (Object)Array( "bank_code" => "247", "bank_name" => "BANCO UBS WARBURG S/A" ),
        //"249" => (Object)Array( "bank_code" => "249", "bank_name" => "BANCO INVESTCRED SA" ),
        //"250" => (Object)Array( "bank_code" => "250", "bank_name" => "BANCO SCHAHIN S.A." ),
        //"252" => (Object)Array( "bank_code" => "252", "bank_name" => "BANCO FININVEST SA" ),
        //"254" => (Object)Array( "bank_code" => "254", "bank_name" => "BANCO PARANA BANCO SA" ),
        //"258" => (Object)Array( "bank_code" => "258", "bank_name" => "BANCO INDUSCRED SA" ),
        //"262" => (Object)Array( "bank_code" => "262", "bank_name" => "BANCO BOREAL S/A" ),
        //"263" => (Object)Array( "bank_code" => "263", "bank_name" => "BANCO CACIQUE SA" ),
        //"265" => (Object)Array( "bank_code" => "265", "bank_name" => "BANCO FATOR SA" ),
        //"266" => (Object)Array( "bank_code" => "266", "bank_name" => "BANCO CEDULA SA" ),
        //"275" => (Object)Array( "bank_code" => "275", "bank_name" => "BANCO REAL SA" ),
        //"291" => (Object)Array( "bank_code" => "291", "bank_name" => "BANCO DE CREDITO NACIONAL SA" ),
        //"294" => (Object)Array( "bank_code" => "294", "bank_name" => "BANCO DE CRED. REAL DO R.G.S SA" ),
        //"300" => (Object)Array( "bank_code" => "300", "bank_name" => "BANCO DE LA NACION ARGENTINA SA" ),
        //"304" => (Object)Array( "bank_code" => "304", "bank_name" => "BANCO PONTUAL SA" ),
        //"318" => (Object)Array( "bank_code" => "318", "bank_name" => "BANCO BMG COMERCIAL S.A." ),
        //"320" => (Object)Array( "bank_code" => "320", "bank_name" => "BANCO INDUSTRIAL E COMERCIAL SPAULO SA" ),
        "341" => (Object)Array( "bank_code" => "341", "bank_name" => "BANCO ITAU S/A" ),
        //"347" => (Object)Array( "bank_code" => "347", "bank_name" => "BANCO SUDAMERIS BRASIL SA" ),
        //"351" => (Object)Array( "bank_code" => "351", "bank_name" => "BANCO BOZANO SIMONSEN SA" ),
        "353" => (Object)Array( "bank_code" => "353", "bank_name" => "BANCO SANTANDER BRASIL S.A." ),
        //"356" => (Object)Array( "bank_code" => "356", "bank_name" => "BANCO ABN AMRO SA" ),
        //"366" => (Object)Array( "bank_code" => "366", "bank_name" => "BANCO SOGERAL SA" ),
        //"370" => (Object)Array( "bank_code" => "370", "bank_name" => "BANCO EUROPEU PARA A AMERICA LATINA SA" ),
        //"375" => (Object)Array( "bank_code" => "375", "bank_name" => "BANCO FENICIA SA" ),
        //"376" => (Object)Array( "bank_code" => "376", "bank_name" => "BANCO CHASE MANHATTAN SA" ),
        //"389" => (Object)Array( "bank_code" => "389", "bank_name" => "BANCO MERCANTIL DO BRASIL SA" ),
        //"392" => (Object)Array( "bank_code" => "392", "bank_name" => "BANCO MERCANTIL-FINASA S.A." ),
        //"394" => (Object)Array( "bank_code" => "394", "bank_name" => "BANCO MERCANTIL DE CREDITO SA" ),
        "399" => (Object)Array( "bank_code" => "399", "bank_name" => "HSBC BANK BRASIL S.A." ),
        //"409" => (Object)Array( "bank_code" => "409", "bank_name" => "BANCO UNIBANCO SA" ),
        //"412" => (Object)Array( "bank_code" => "412", "bank_name" => "BANCO CAPITAL S.A" ),
        //"415" => (Object)Array( "bank_code" => "415", "bank_name" => "BANCO NACIONAL SA" ),
        //"422" => (Object)Array( "bank_code" => "422", "bank_name" => "BANCO SAFRA SA" ),
        "424" => (Object)Array( "bank_code" => "424", "bank_name" => "BANCO SANTANDER NOROESTE S.A." ),
        //"453" => (Object)Array( "bank_code" => "453", "bank_name" => "BANCO RURAL SA" ),
        //"456" => (Object)Array( "bank_code" => "456", "bank_name" => "BANCO DE TOKYO-MITSUBISHI BRASIL SA" ),
        //"464" => (Object)Array( "bank_code" => "464", "bank_name" => "BANCO SUMITOMO BRASILEIRO SA" ),
        //"472" => (Object)Array( "bank_code" => "472", "bank_name" => "BANCO LLOYDS BANK PLC" ),
        //"473" => (Object)Array( "bank_code" => "473", "bank_name" => "BANCO FINANCIAL PORTUGUES SA" ),
        //"477" => (Object)Array( "bank_code" => "477", "bank_name" => "CITIBANK N.A." ),
        //"479" => (Object)Array( "bank_code" => "479", "bank_name" => "BANKBOSTON BCO MULTIPLO S.A." ),
        //"480" => (Object)Array( "bank_code" => "480", "bank_name" => "BANCO WACHOVIA S.A" ),
        //"487" => (Object)Array( "bank_code" => "487", "bank_name" => "BANCO DEUTSCHE BANK SA" ),
        //"488" => (Object)Array( "bank_code" => "488", "bank_name" => "BANCO MORGAN GUARANTY TRUST COMPANY" ),
        //"489" => (Object)Array( "bank_code" => "489", "bank_name" => "BANCO FRANCES INTERNACIONAL BRASIL S.A." ),
        //"492" => (Object)Array( "bank_code" => "492", "bank_name" => "BANCO NMB POSTBANK GROEP N.V. SA" ),
        //"493" => (Object)Array( "bank_code" => "493", "bank_name" => "BANCO UNION BRASIL S.A." ),
        //"494" => (Object)Array( "bank_code" => "494", "bank_name" => "BANCO LA REPUBL.ORIENTAL DEL URUGUAY SA" ),
        //"495" => (Object)Array( "bank_code" => "495", "bank_name" => "BANCO LA PROVINCIA DE BUENOS AIRES SA" ),
        //"496" => (Object)Array( "bank_code" => "496", "bank_name" => "BANCO EXTERIOR DE ESPANA SA" ),
        //"502" => (Object)Array( "bank_code" => "502", "bank_name" => "BANCO SANTANDER DE NEGOCIOS S.A." ),
        //"505" => (Object)Array( "bank_code" => "505", "bank_name" => "BANCO CREDIT SUISSE FIRST BOSTON GARANTI" ),
        //"600" => (Object)Array( "bank_code" => "600", "bank_name" => "BANCO LUSO BRASILEIRO SA" ),
        //"602" => (Object)Array( "bank_code" => "602", "bank_name" => "BANCO PATENTE SA" ),
        //"604" => (Object)Array( "bank_code" => "604", "bank_name" => "BANCO INDUSTRIAL DO BRASIL S/A" ),
        //"607" => (Object)Array( "bank_code" => "607", "bank_name" => "BANCO SANTOS NEVES S.A." ),
        //"610" => (Object)Array( "bank_code" => "610", "bank_name" => "BANCO VR S.A" ),
        //"611" => (Object)Array( "bank_code" => "611", "bank_name" => "BANCO PAULISTA S.A." ),
        //"612" => (Object)Array( "bank_code" => "612", "bank_name" => "BANCO GUANABARA SA" ),
        //"613" => (Object)Array( "bank_code" => "613", "bank_name" => "BANCO PECUNIA S.A." ),
        //"618" => (Object)Array( "bank_code" => "618", "bank_name" => "BANCO TENDENCIA S.A." ),
        "623" => (Object)Array( "bank_code" => "623", "bank_name" => "BANCO PANAMERICANO S.A." ),
        //"625" => (Object)Array( "bank_code" => "625", "bank_name" => "BANCO ARAUCARIA SA" ),
        //"626" => (Object)Array( "bank_code" => "626", "bank_name" => "BANCO FICSA SA" ),
        //"630" => (Object)Array( "bank_code" => "630", "bank_name" => "BANCO INTERCAP SA" ),
        //"633" => (Object)Array( "bank_code" => "633", "bank_name" => "BANCO RENDIMENTO S.A." ),
        //"634" => (Object)Array( "bank_code" => "634", "bank_name" => "BANCO TRIANGULO SA" ),
        //"637" => (Object)Array( "bank_code" => "637", "bank_name" => "BANCO SOFISA SA" ),
        //"638" => (Object)Array( "bank_code" => "638", "bank_name" => "BANCO PROSPER SA" ),
        //"641" => (Object)Array( "bank_code" => "641", "bank_name" => "BANCO BILBAO VIZCAYA ARGENTARIA BRASIL S" ),
        //"643" => (Object)Array( "bank_code" => "643", "bank_name" => "BANCO PINE S.A." ),
        //"650" => (Object)Array( "bank_code" => "650", "bank_name" => "BANCO PEBB S.A" ),
        //"653" => (Object)Array( "bank_code" => "653", "bank_name" => "BANCO INDUSVAL SA" ),
        //"654" => (Object)Array( "bank_code" => "654", "bank_name" => "BANCO A.J. RENNER SA" ),
        //"655" => (Object)Array( "bank_code" => "655", "bank_name" => "BANCO VOTORANTIM S.A. SA" ),
        //"656" => (Object)Array( "bank_code" => "656", "bank_name" => "BANCO MATRIX S.A. SA" ),
        //"658" => (Object)Array( "bank_code" => "658", "bank_name" => "BANCO PORTO REAL S.A." ),
        //"702" => (Object)Array( "bank_code" => "702", "bank_name" => "BANCO SANTOS SA" ),
        //"707" => (Object)Array( "bank_code" => "707", "bank_name" => "BANCO DAYCOVAL SA" ),
        //"719" => (Object)Array( "bank_code" => "719", "bank_name" => "BANCO BANIF PRIMUS S/A" ),
        //"720" => (Object)Array( "bank_code" => "720", "bank_name" => "BANCO MAXINVEST S.A." ),
        //"721" => (Object)Array( "bank_code" => "721", "bank_name" => "BANCO CREDIBEL S.A." ),
        //"722" => (Object)Array( "bank_code" => "722", "bank_name" => "BANCO INTERIOR DE SAO PAULO S.A." ),
        //"725" => (Object)Array( "bank_code" => "725", "bank_name" => "BANCO FINANSINOS SA" ),
        //"729" => (Object)Array( "bank_code" => "729", "bank_name" => "BANCO FONTE-CINDAM" ),
        //"733" => (Object)Array( "bank_code" => "733", "bank_name" => "BANCO DAS NACOES SA" ),
        //"734" => (Object)Array( "bank_code" => "734", "bank_name" => "BANCO GERDAU SA" ),
        //"735" => (Object)Array( "bank_code" => "735", "bank_name" => "BANCO POTTENCIAL S.A." ),
        //"737" => (Object)Array( "bank_code" => "737", "bank_name" => "BANCO THECA SA" ),
        //"738" => (Object)Array( "bank_code" => "738", "bank_name" => "BANCO MORADA SA" ),
        //"739" => (Object)Array( "bank_code" => "739", "bank_name" => "BANCO GALVAO DE NEGOCIOS SA" ),
        //"740" => (Object)Array( "bank_code" => "740", "bank_name" => "BANCO BARCLAYS E GALICIA S.A." ),
        //"741" => (Object)Array( "bank_code" => "741", "bank_name" => "BANCO RIBEIRAO PRETO SA" ),
        //"742" => (Object)Array( "bank_code" => "742", "bank_name" => "BANCO EQUATORIAL SA" ),
        //"743" => (Object)Array( "bank_code" => "743", "bank_name" => "BANCO EMBLEMA SA" ),
        //"744" => (Object)Array( "bank_code" => "744", "bank_name" => "BANKBOSTON N.A." ),
        //"745" => (Object)Array( "bank_code" => "745", "bank_name" => "BANCO CITIBANK S.A." ),
        //"746" => (Object)Array( "bank_code" => "746", "bank_name" => "BANCO MODAL SA" ),
        //"747" => (Object)Array( "bank_code" => "747", "bank_name" => "BANCO RABOBANK INTERNATIONAL BR S.A." ),
        //"748" => (Object)Array( "bank_code" => "748", "bank_name" => "BANCO COOPERATIVO SICREDI S/A" ),
        //"749" => (Object)Array( "bank_code" => "749", "bank_name" => "BR BANCO MERCANTIL S.A." ),
        //"750" => (Object)Array( "bank_code" => "750", "bank_name" => "BANCO REPUBLIC NATIONAL OF NEW YORK S/A." ),
        //"751" => (Object)Array( "bank_code" => "751", "bank_name" => "DRESDNER BANK BRASIL S.A. BANCO MULTIPL" ),
        //"752" => (Object)Array( "bank_code" => "752", "bank_name" => "BANQUE NATIONALE PARIS BRASIL S.A" ),
        //"753" => (Object)Array( "bank_code" => "753", "bank_name" => "BANCO COMERCIAL URUGUAI S.A." ),
        //"755" => (Object)Array( "bank_code" => "755", "bank_name" => "BANCO MERRILL LYNCH S.A." ),
        //"756" => (Object)Array( "bank_code" => "756", "bank_name" => "BANCO COOPERATIVO DO BRASIL S.A." ),
        //"757" => (Object)Array( "bank_code" => "757", "bank_name" => "BANCO KEB DO BRASIL S.A." ),
        //"758" => (Object)Array( "bank_code" => "758", "bank_name" => "BANCO FRANCES E BRASILEIRO" ),
        //"759" => (Object)Array( "bank_code" => "759", "bank_name" => "CONFIANÇA BANESTES" )
    );
    $smarty->assign( "l_bank", $l_bank );

    $smarty->assign( "year", date("Y") );

	if( isset( $_SESSION["user_id"] ) ){
        $user = new User(array(
            "user_id"         => $_SESSION["user_id"],
            "get_UserProfile" => 1,
            "get_UserProfileAccess" => 1,
            "get_Person"      => 1,
            "noJson"          => 1
        ));
        $user = $user->get();
        $user->UserProfile->UserProfileAccess = treeAccess($user->UserProfile->UserProfileAccess);
        $smarty->assign( "user", $user);
	}
